Strings.zh-CN.resx

complete translation

---

Strings.zh-CN.resx

I think "Stats" should be translate "统计".

Fixed translation error

---

Strings.zh-TW.resx

add new language

---

Strings.zh-CN.resx

Essential Corrections were made.
PS: Sorry for the delay because of my unfamiliarity with github.

Compact Update

---

Strings.zh-CN.resx

Translated last few lines( ln2697-ln2744) from English version, 
and line numbers are in accord with English version now.

Keeping up with English Version

---

Strings.ja-JP.resx

Hello.
This file is translation from English into Japanese.
According to https://msdn.microsoft.com/en-us/library/cc233982.aspx, 
this file is named as Strings.ja-JP.resx.
Thank, you.

translation into Japanese

---

Strings.ko-KR.resx

Still WIP
TODO
- Fill missing values
- Handle underscore(_) character
- Do context checking
- Do double-checking

Add Korean translation

---

Strings.ru-RU.resx

Please remove the repeated lines, if possible. For example, many lines "all".

Update ru-RU 05.04.17

---

Strings.pl-PL.resx

Added Polish language. (99%)

---

Strings.pl-PL.resx

Polish update 14.05.2017

---

Strings.zh-TW.resx

Update zh-TW to 5/28

---

Strings.de-DE.resx

Add german translation

---

Strings.resx

Various spelling fixes in original English strings.
Some misquoted XML fixes too.

Various spelling fixes in English strings

---

Strings.ru-RU.resx

ru-RU 1.7.17

---

Strings.de-DE.resx
Strings.ja-JP.resx
Strings.ko-KR.resx
Strings.pl-PL.resx
Strings.pt-BR.resx
Strings.pt-PT.resx
Strings.ru-RU.resx
Strings.uk-UA.resx
Strings.zh-CN.resx
Strings.zh-TW.resx

HearthSim/Hearthstone-Deck-Tracker#3322

Use single localized CheckBox for charts legends in Stats

---

Strings.fr-FR.resx

Initial French translation.
I would need a custom build though, so I can check the UI for size issues, etc.

Initial French translation

---

Strings.fr-FR.resx

French update for Knights of the Frozen Throne (+ some other updates)

French update for Knights of the Frozen Throne

---

Strings.ru-RU.resx

Update ru-RU 9.8.17

---

Strings.ja-JP.resx

added some strings about updating HDT.
HDTの更新に関する翻訳を追加しました。
Temporary translated as below.
暫定的に、下記の通り統一的に訳してみました。
update > 更新
modify > 変更
check > 確認

add "update" strings

---

Strings.zh-TW.resx

Update zh-TW to 2017/8/26

---

Strings.pl-PL.resx
Strings.resx

Related commit: https://github.com/HearthSim/Hearthstone-Deck-Tracker/pull/3434

Add strings for SelectLanguageDialog

---

Strings.ja-JP.resx

1. fixed some expressions to natural Japanese.
いくつかの表現を自然な日本語に修正しました。
2. standarized some braces in Japanese to "「」"
括弧を「」に統一しました。

fix some strings in ja-JP

---

Strings.pl-PL.resx

Polish update 27.10.2017

---

Strings.ko-KR.resx

Please tell me if there is any problem or TODO.

Update translation ko-KR

---

Strings.fr-FR.resx

French update for new twitch extension strings + some small fixes

French update for Twitch Extension

---

Strings.zh-TW.resx

zh-TW update to 11/26

---

Strings.ko-KR.resx

I translated some words in IMPORT menu and DECK EDITOR menu to ko-KR.
Have a nice day.

Update translation ko-KR (2)

---

Strings.ko-KR.resx

Translate part of Dungeon run and other things.

Update ko-KR 12/17/17

---

Strings.pl-PL.resx
Strings.resx

Strings update + Polish update 12.04.2018
